locale: zh_cn
decimal_format: '#,##0.00'
strict: false
economy: vault
chatHook: true
updateTicks: 20
auction:
  listingPrice: 0.0
  listingRate: 0.0
  listingCooldown: 0d0h0m0s
  listingDuration: 7d0h0m
  expiredDuration: 14d0h0m
  unclaimedDuration: 90d0h0m
  cleanupDuration: 0d24h0m
  soldDuration: 365d0h0m
  unclaimedCheckDuration: 0d0h5m
  unclaimedCheckOnWorldChange: true
  preventCreative: false
  preventSpectator: true
  preventFilledContainers: false
  minSellPrice: 1.0
  maxSellPrice: 100000.0
  salesTax: 3.7
  maxSalesTax: 100000.0
  allowDamagedItems: true
  defaultMaxListings: 10
  sortOrder: oldest
  discord_channel: auctionhouse
  multiworld: false
  groupWorlds: false
  replaceUUIDs: false
  replacePlayerNames: false
  dropAtFeet: false
  showSeconds: true
  spawnerInfo: true
  integerPrice: false
  showRepairCost: false
announce:
  chat:
    listings: false
    purchases: false
  action_bar:
    listings: false
    purchases: false
  discord:
    listings: false
    purchases: false
restricted_items:
  '0':
    item: minecraft:bedrock
  '1':
    item: minecraft:barrier
  '2':
    item: minecraft:command_block
  '3':
    item: minecraft:structure_block
  example:
    name: \u00a7cVorpal Sword
    item: minecraft:diamond_sword
    lore:
    - Special Item
    - Does not list in AuctionHouse
    enchantments:
    - ench: minecraft:sharpness
      level: 10
    - ench: minecraft:unbreaking
      level: 3
    - ench: minecraft:looting
      level: 3
    - ench: minecraft:fire_aspect
      level: 2
    unbreakable: true
    custom_model_data: 1
  mcmmo:
    lore:
    - mcMMO Ability Tool
  mcmmo_ability:
    persistent_data:
      mcmmo:super_ability_boosted: 0
sounds:
  click: ui.button.click
  fail: entity.villager.no
  drop: entity.player.burp
  sold: block.note_block.chime
buttons:
  exit: minecraft:iron_door
  back: minecraft:iron_door
  previous: minecraft:paper
  sort_listings: minecraft:sunflower
  next: minecraft:paper
  info: minecraft:book
  howto: minecraft:emerald
  return_all: minecraft:flower_pot
  player_listings: minecraft:diamond
  expired_listings: minecraft:poisonous_potato
  sold_items: minecraft:gold_ingot
  clear: minecraft:barrier
  confirm: minecraft:lime_stained_glass_pane
  cancel: minecraft:red_stained_glass_pane
triggers:
  sign: '[AuctionHouse]'
  block_name: Auction House
  entity_name: Auction House
commands:
  exit: msg %player% Exiting AuctionHouse
log:
  listed: true
  sold: true
  cancelled: true
  returned: true
  dropped: true
  purged: true
anticheat:
  spam_check: true
disabled-worlds: []
configVersion: 33
