# cStats collects some data for plugin authors like how many servers are using their plugins.
# To honor their work, you should not disable it.
# This has nearly no effect on the server performance!
# Check out https://cstats.iroselle.com/ to learn more :)

enabled: true
serverUuid: 5edfd26c-8740-4a4b-ad31-95b8db585b32
logFailedRequests: false
logSentData: false
logResponseStatusText: false
