################################
#             INFO             #
################################
# Thanks for using Mobs To Eggs!
# You can find more plugin information on the spigot page https://www.spigotmc.org/resources/69425/
# Discord support is provided at http://discord.sugar.fyi
#################################
#            General            #
#################################
# Multiple languages are supported.
# Please see https://gitlab.com/sugarfyi-team/public/mobstoeggs-public/-/wikis/Language-Files for more info on supported languages.
# Note: The plugin will attempt to use the language file set below, if this fails or the file doesn't exist, it will revert to 'en'.
language: "en"
global-values:
  # Should mob eggs be allowed to change the mob spawner type when a spawner is right-clicked?
  # This is useful if you have other plugins that handle spawner changing.
  # Note: you won't be able to save mob data on a spawner when this is set false.
  change-spawners: true
# Periodically check if there is a new update for Mobs To Eggs. This will send a message to the console when an update is found.
check-for-updates: true
# If your 'projectile-type' below is set as an "Egg", this option allows you to allow/deny baby chickens from hatching when a chicken egg is thrown.
# Note: This will disable baby chicken hatching from ALL thrown chicken eggs when set false.
enable-chicken-egg-hatching: false
###################################
#   Catch Capsule Modifications   #
###################################
# Here you can edit the catch capsule to create a custom projectile to throw at mobs to catch them in mob spawn eggs.
# projectile-type = The projectile that is collected and thrown
# item = The item the catch capsule will appear as when thrown.
# data = CustomModelData for a resource pack. Set to '-1' if you don't use it.
# name = "the name of the catch capsule" (colour codes supported).
# lore = the description (lore) placed on the item.
# Example:
#  capsule:
#   projectile-type: Snowball
#   item: Egg
#   data: 1234567
#   name: "&aA green egg"
#   lore: ["&cLore line 1", "&6Lore line 2", "&eLore line 3", "etc"]
capsule:
  projectile-type: Egg
  item: Egg
  data: -1
  name: ""
  lore: []
##################################
#   Capsule Throwing Behaviour   #
##################################
# You can change the ways that you use your capture capsule to catch mobs.
# throw = launching the capture capsule at the mob as a projectile (such as throwing an egg).
# punch = punch (left-click) the mob with the capture capsule to catch it.
# You can have all catch methods set true, but you cannot have all set false.
catch-method:
  throw: true
  punch: false
# If you have 'throw: false' set above, then nothing below will be used.
# What effects do you want to play around the player when they throw a catch capsule?
throw-effects:
  # Do you want to use throw effects below?
  use-throw-effects: true
  # Particle to play on the player
  particle-effect: CRIT
  particle-count: 5
  sound: ENTITY_ENDER_DRAGON_FLAP
  sound-volume: 3
  sound-pitch: 1.8
##################################
#     Mob Catching Behaviour     #
##################################
# Do you want baby mobs to be caught?
catch-baby-mobs: false
# Do you want sheared mobs to be caught?
# Example: sheep.
catch-sheared-mobs: true
# Do you want tamed mobs to be caught? (These mobs can be caught by everyone, it is best to keep this false to avoid pet theft)
# Example: wolf, cat, donkey, horse, llama, parrot, mule, etc.
catch-tamed-mobs: false
# Do you want mobs that have been named with a name tag or anvil to be caught?
catch-named-mobs: true
# If the above is set to 'true', do you want named mobs to keep their names?
# If this value is set to 'false' the name will be removed.
named-mobs-keep-name: true
# Do you want to save the data of a mob to the mob spawn egg that drops?
# This is found in each mob file under mobs.yml 'egg.egg-data.data'
# Example: sheep colour, villager professions, angry bees, sheared sheep, etc.
# The data that is saved can be edited for each mob individually in their mob file.
save-mob-data: true
#################################
#      Catching protection      #
#################################
# Enter a list of worlds you want to whitelist/blacklist (the value you set in 'catch-only-in-listed-worlds').
# Set this to 'worlds: []' to disable.
worlds: []
# If 'false' the list of 'worlds' will act as a blacklist (can't catch in listed worlds, but can in any other worlds).
# If 'true' the list of 'worlds' will act as a whitelist (can only catch in listed worlds, and can't catch in any other worlds).
catch-only-in-listed-worlds: false
# Enter a list of worldguard regions you want to whitelist/blacklist (the value you set in 'catch-only-in-listed-regions').
# Set this to 'regions: []' to disable.
regions: []
# If 'false' the list of 'regions' will act as a blacklist (can't catch in listed regions, but can in any other regions).
# If 'true' the list of 'regions' will act as a whitelist (can only catch in listed regions, and can't catch in any other regions).
catch-only-in-listed-regions: false
##################################
#       Costs for catching       #
##################################
# Setting 'enable-item-cost' and 'enable-money-cost' to false will make catching free.
# You can edit the item and money cost per-mob in the mobs.yml file.
# Do you want to make catching mobs cost an item from the player's inventory?
enable-item-cost: false
# Do you want to make catching mobs cost money? (You need Vault and an economy plugin installed)
enable-money-cost: false
# Do you want to ignore costs for players in creative mode?
ignore-creative-cost: true
# Do you want the catch capsule to be refunded when the catch is not successful?
# This acts as a way to only take the capsule item when the mob is caught.
# Note: this will only work if the mob is hit by the capsule and has a chance to be caught.
refund-capsule-on-unsuccessful-capture: false
##################################
#        Catching Effects        #
##################################
# You can set the effects that play on a mob when it is successfully captured
catch-effects:
  # Do you want to use the catch effects below?
  use-catch-effects: true
  # Particle effects to play at the mob when caught
  particle-effect: EXPLOSION_NORMAL
  particle-count: 20
  particle-x: 0.5
  particle-y: 0.5
  particle-z: 0.5
  # Sounds played when mob is caught
  sound: ITEM_BOTTLE_FILL_DRAGONBREATH
  sound-volume: 3
  sound-pitch: 2
  # Sounds played when the mob fails to be caught
  sound-fail: ENTITY_LLAMA_EAT
  sound-fail-volume: 3
  sound-fail-pitch: 1.5
##############################
#        Plugin Value        #
##############################
# There is no need to edit config-version at all. The plugin will automatically change this when required!
# Note: any manual edits to this value can delete your config files!
config-version: 1.6.6_1